### ISSUE TITLE
loop seems necessary

### ISSUE THREAD

**Issue by ioannad** [studio/studio#43]
This code works:
`with import <studio>;
raptorjit.run ''
 for M=1,100 do
	x = 1
end
 ''`

while this:
`with import <studio>;
raptorjit.run ''
	x = 1
 ''`
drops me into the Pharo debugger (AssertionFailure).

The loop seems somehow necessary, but the error window is confusing. 
@eugeneia says there's no trace being recorded otherwise.

**Comment by lukego** [comment]
Marked as a bug. Thanks for the report.

This seems to be due to a mismatch between the backend and frontend parts of the RaptorJIT support. The [contract between them](https://hydra.snabb.co/build/1734973/download/1/studio.html#product-raptorjit-vm-dump) says that the `audit.log` file must exist, but in practice the backend is [treating this file as optional]((https://github.com/studio/studio/blob/master/backend/raptorjit/default.nix#L41-L43)) while the frontend is probably assuming that it is there.

Likely a good solution is to update the contract ("product definition") to say that the `audit.log` file is indeed optional and to make the frontend Pharo code handle that gracefully.
